services:

  cli:
    container_name: cli
    build:
      context: ./cli
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-}
        COMPOSER_VERSION: ${COMPOSER_VERSION:+ --version=${COMPOSER_VERSION}}
        NODE_VERSION: ${NODE_VERSION:-lts}
    user: ${CUID:-0}:${CGID:-0}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - type: bind
        source: ./project
        target: /project
    networks:
      - php-docker-dev-env

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:+${PHP_VERSION}-}
        XDEBUG_VERSION: ${XDEBUG_VERSION:+-${XDEBUG_VERSION}}
    user: ${CUID:-0}:${CGID:-0}
    restart: unless-stopped
    environment:
      PHP_IDE_CONFIG: "serverName=${IDE_SERVER_NAME:-php-docker-dev-env}"
    volumes:
      - type: bind
        source: ./project
        target: /project
      - type: bind
        source: ./xdebug/xdebug.ini
        target: /usr/local/etc/php/conf.d/xdebug.ini
      - type: bind
        source: ./xdebug/logs
        target: /xdebug-logs
    networks:
      - php-docker-dev-env
    extra_hosts:
      host.docker.internal: host-gateway

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    volumes:
      - type: bind
        source: ./project
        target: /project
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
    networks:
      - php-docker-dev-env

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_DATABASE: project
      TZ: ${TZ}
    secrets:
      - mysql-root-password
    volumes:
      - php-docker-dev-env-mysql-data:/var/lib/mysql
    networks:
      - php-docker-dev-env

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      TZ: ${TZ}
    depends_on:
      - mysql
    networks:
      - php-docker-dev-env

  production:
    build:
      context: .
      dockerfile: ./build-app/production.Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:+${PHP_VERSION}-}
    profiles:
      - production

  stand-alone:
    build:
      context: .
      dockerfile: ./build-app/stand-alone.Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:+${PHP_VERSION}-}
    profiles:
      - stand-alone

secrets:
  mysql-root-password:
    file: ./secrets/mysql_root_password.txt

volumes:
  php-docker-dev-env-mysql-data:
    name: php-docker-dev-env-mysql-data

networks:
  php-docker-dev-env:
    name: php-docker-dev-env
    driver: bridge